moai:
  initialized: true
  initialized_at: '2025-12-19T00:00:00Z'
  version: 1.7.0
project:
  name: stock-manager
  mode: personal
  description: ''
  created_at: '2026-01-23 21:22:48'
  optimized: false
  template_version: 1.7.0
